<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseWindowsService>true</UseWindowsService>
    <ImplicitUsings>enable</ImplicitUsings>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>annotations</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <StartupObject>JiaoLongWMI.Program</StartupObject>
    <ApplicationIcon>electron-icon.ico</ApplicationIcon>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <SignAssembly>False</SignAssembly>
    <PackAsTool>False</PackAsTool>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	<PublishSingleFile>true</PublishSingleFile>
	<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
	<LangVersion>default</LangVersion>
	<PackageProjectUrl>https://github.com/GaoXanSheng/JiaoLongWMI</PackageProjectUrl>
	<PackageIcon>electron-icon.ico</PackageIcon>
	<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	<NeutralLanguage>zh-Hans</NeutralLanguage>
	<Title>JiaoLongWMI</Title>
	<Authors>GaoXanSheng</Authors>
	<Description>JiaoLongWMI</Description>
	<Copyright>GaoXanSheng</Copyright>
	<PackageLicenseUrl>https://github.com/GaoXanSheng/JiaoLongWMI/blob/master/LICENSE</PackageLicenseUrl>
	<RepositoryUrl>git@github.com:GaoXanSheng/JiaoLongWMI.git</RepositoryUrl>
	<RepositoryType>Git</RepositoryType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Optimize>False</Optimize>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="drivers\WinIo64.sys" />
		<EmbeddedResource Include="drivers\WinIo64.dll" />
	</ItemGroup>

  <ItemGroup>
    <Content Include="electron-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.5-pre396" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.5" />
    <PackageReference Include="Namotion.Reflection" Version="3.2.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="System.Diagnostics.Tracing" Version="4.3.0" />
    <PackageReference Include="System.Management" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="System.Management" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="app.manifest" />
    <ApplicationDefinition Include="app.manifest">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </ApplicationDefinition>
  </ItemGroup>

</Project>
