### LOGO灯关
POST http://localhost:9871/
Content-Type: application/json

{
  "type": "LogoLight",
  "method": "Set",
  "args":["OFF"]
}
### LOGO灯开
POST http://localhost:9871/
Content-Type: application/json

{
  "type": "LogoLight",
  "method": "Set",
  "args":["ON"]
}