namespace JiaoLongWMI.Constants
{
    public enum EventName : byte
    {
        Reserved_1 = 1,
        Reserved_2 = 2,
        Reserved_3 = 3,
        AirPlaneMode = 4,
        RGBKeyboardBrightness = 5,
        TouchPadState = 6,
        FnState = 7,
        RGBKeyboardMode = 8,
        CapsLkState = 9,
        AmbientlightState = 10,
        CalculatorStart = 11,
        DefaultBrowserStart = 12,
        NumLockState = 13,
        ScrlockState = 14,
        SystemPerMode = 15,
        FN_J = 16,
        FN_F = 17,
        FN_0 = 18,
        FN_1 = 19,
        FN_2 = 20,
        FN_3 = 21,
        FN_4 = 22,
        FN_5 = 24,
        PanelRefreshRate = 25,
        CPUFanSpeed = 26,
        GPUFanSpeed = 32,
        WinKeyLock = 33,
        Reserved_22 = 34,
        Reserved_23 = 35,
        Reserved_24 = 36,
        Reserved_25 = 37,
        Reserved_26 = 38,
        Reserved_27 = 39,
        Reserved_28 = 40,
        Reserved_29 = 41,
    }
}
