namespace JiaoLong16Pro.BLD.WMIOperation
{
    public enum WMIEventName : byte
    {
        Reserved_1 = 1,
        Reserved_2,
        Reserved_3,
        AirPlaneMode,
        RGBKeyboardBrightness,
        TouchPadState,
        FnState,
        RGBKeyboardMode,
        CapsLkState,
        AmbientlightState,
        CalculatorStart,
        DefaultBrowserStart,
        NumLockState,
        ScrlockState,
        SystemPerMode,
        FN_J,
        FN_F,
        FN_0,
        FN_1,
        FN_2,
        FN_3,
        FN_4,
        FN_5 = 24,
        PanelRefreshRate,
        CPUFanSpeed,
        GPUFanSpeed = 32,
        WinKeyLock,
        Reserved_22,
        Reserved_23,
        Reserved_24,
        Reserved_25,
        Reserved_26,
        Reserved_27,
        Reserved_28,
        Reserved_29
    }
}
